export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_GET_USER_DETAIL = "AUTH_GET_USER_DETAIL";

export const EXERCISE_START = "EXERCISE_START";
export const EXERCISE_SUCCESS = "EXERCISE_SUCCESS";
export const EXERCISE_SUCCESS_FETCH = "EXERCISE_SUCCESS_FETCH";
export const EXERCISE_FAIL = "EXERCISE_FAIL";
export const EXERCISE_CLEARED = "EXERCISE_CLEARED";
export const EXERCISE_SET_CLIENTID = "EXERCISE_SET_CLIENTID";
export const EXERCISE_UPDATE_FORM = "EXERCISE_UPDATE_FORM";

export const GENERAL_LANGUAGE_SET = "GENERAL_LANGUAGE_SET";