# Generated by Django 2.2.3 on 2019-12-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20191016_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
