# Generated by Django 2.2.3 on 2019-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='password',
        ),
        migrations.RemoveField(
            model_name='program',
            name='uuid',
        ),
        migrations.AddField(
            model_name='program',
            name='branch',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='identify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='intro',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='law',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='phone',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=80),
        ),
    ]
